name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Project Version
      run: |
        echo "VERSION=$(date +'%d-%m-%Y-%H-%M')" >> $GITHUB_ENV
    - name: Change POM Version
      run: |
        echo "VERSION : $VERSION"
        mvn -B versions:set -DnewVersion=$VERSION
    - name: Deploy Artifact
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Docker Image generation
      run: mvn spring-boot:build-image -Dgithub.sha=${{ github.sha }}

    - name: Log in to the ghcr.io Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Images
      run: |
        docker images
        docker push -a ghcr.io/$GITHUB_REPOSITORY