name: delete-old-package

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'
jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
    - name: Clean Maven Package
      uses: actions/delete-package-versions@v3
      with:
        owner: ${{ github.actor }}
        repo: 'petstore-user'
        package-name: 'com.samitkumarpatel.petstore.petstore-user'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean Docker Image
      uses: actions/delete-package-versions@v3
      with:
        owner: ${{ github.actor }}
        repo: 'petstore-user'
        package-name: 'petstore-user'
        token: ${{ secrets.GITHUB_TOKEN }}